#!/bin/bash

# Make sure job is submitted directly
if [ ! -z ${SLURM_JOB_ID+x} ]; then
   echo "This script should be executed directly, not with sbatch."
   exit 1
fi

# allows user to specify a job to wait for completion before running any of these scripts
if [ ! -z "$1" ]; then
  previous_job=$1
else
  previous_job=1 # run first job immediately
fi

# Create logging directory
log_dir=logs/genetic_score_training/
mkdir -p $log_dir

# Step 1: curate list of QTLs to extract from the genotype data
# First argument in python script is the omics platform name (i.e. SomaScan, Olink, Metabolon, Nightingale and RNAseq)
# and the second argument is the index of a trait for training in the platform
# the 3th to 6th arguments are the priors for the BR method

mkdir -p geno_files/ml_inputs

score_training=$(sbatch --dependency afterany:$previous_job \
								--parsable \
								--account INOUYE-COVID19-SL2-CPU \
								--job-name "score train" \
								--time 36:0:0 \
								-c 32 -N 1 \
                --output $log_dir/score_training_%j.o \
                --error $log_dir/score_training_%j.e \
								--partition skylake-himem \
                --wrap "Python scripts/05_genetic_score_training/01_run_omics_pgs_training with_br.py SomaScan 1 0.000001 0.000001 0.000001 0.000001")



echo "Submitted jobs $score_training"

